### ISSUE TITLE
South Sudan is missing in the countries list

### ISSUE THREAD

**Issue by papandreou** [papandreou/inter#14]
For a territory to be classified as a country, it currently has to be listed in https://github.com/papandreou/inter/blob/master/worldInfo/countries.csv and not be historical, nor a subdivision. The list appears to be a a bit outdated (the timestamps in the last column of the file say 2007-10-24). South Sudan declared its independence in 2011, and there has probably been other changes as well.

@bramstein, I think I got the file from you, do you know where I can find an updated version?

CC: @birkestroem

**Comment by bramstein** [comment]
@papandreou It came from a database that I maintained, but has since been shut down (I wasn't running it).

**Comment by mwoc** [comment]
We have another source in https://github.com/papandreou/node-cldr/blob/master/3rdparty/cldr/common/supplemental/supplementalData.xml which has this data, and is more up to date (South Sudan, Serbia, and Montenegro appear as individual states).
@papandreou could we take a look at possibly starting to use that data source instead of countries.csv ?

**Comment by papandreou** [comment]
@mwoc Awesome, I hadn't noticed that. I can't believe there are so many diamond-plated needles to be found in that haystack :)

Yeah, let's work out how we can use that instead of countries.csv. I can help you get started?

**Comment by papandreou** [comment]
Oh, a CLDR 28 release came out in September. I updated to that on master.

**Comment by mwoc** [comment]
- The data currently in regions.json can be extracted from supplementalData territoryContainment
- The data currently in countries.csv can be found in a more accurate version from supplementalData territoryInfo, see https://github.com/papandreou/inter/blob/32d596735c5d5b475d27b1bb238b9680ad0b9434/bin/buildInter#L479

**Comment by mwoc** [comment]
codeMappings/territoryCodes
If an entry does not have a numeric ID, it's not a country, but a(n exceptional) reservation. Sometimes those have an alpha3, but not always. All of those have an alpha2.

territoryContainment/group
Self-explanatory

**Comment by mwoc** [comment]
https://github.com/papandreou/node-cldr/tree/feature/worldInfoFromCldr

**Comment by mwoc** [comment]
Closing through https://github.com/papandreou/inter/commit/7066525aa6e6609a361e932892a7f726e07e6a4a
