### ISSUE TITLE
Add currency precision parameter to renderCurrencyShort

### ISSUE THREAD

**Issue by abugnais** [papandreou/inter#19]
currently renderCurrencyShort has a fixed precision of 2 digits after the decimal point for all currencies example:

renderCurrencyShort(10, 'JPY', 'latin') will render 10.00 which is not correct since JPY does not support decimal digits according to ISO-4217, my suggestion is to add an extra parameter for precision to renderCurrency or add a precision value to each element in the currencies array and let it decide the number of decimal digits for each one.

**Comment by mwoc** [comment]
This got fixed with https://github.com/papandreou/inter/commit/b104ec8a479480426d4cfd8688857f60004da85e
