### ISSUE TITLE
Inter v1.10.0 missing the 'build' folder

### ISSUE THREAD

**Issue by mwoc** [papandreou/inter#21]
For some reason, npm published inter v1.10.0 without having created the 'build' folder, nor erroring out.

```
npm publish
> inter@1.10.0 prepublish /some/local/path
> rm -fr build && ./bin/buildInter --type node -o build --all --golf --jobsize 100
+ inter@1.10.0
```

I've unpublished it now, but have to check tomorrow what's going on.

**Comment by papandreou** [comment]
That sounds really weird. I'm trying my luck with publishing 1.10.1 now.
