### ISSUE TITLE
Update time package

### ISSUE THREAD

**Issue by owcd** [papandreou/inter#22]
Building time@0.11.2 on nodejs@4.2.4 fails

time.target.mk:92: recipe for target 'Release/obj.target/time/src/time.o' failed

Looks like the time package requires an update to 0.11.4 for building fine.

**Comment by papandreou** [comment]
Hmm, seems like time 0.10.4 is not sufficient for it to work with 4.2 and 5: https://travis-ci.org/papandreou/inter/jobs/102569319

Any other ideas?

**Comment by mwoc** [comment]
The travis build says:

"Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements."

So I don't think it's related to the 'time' module. Runs fine locally for me on v4.2.

**Comment by mwoc** [comment]
They write to update .travis.yml to make it work.

**Comment by papandreou** [comment]
@mwoc Ah, nice catch, trying that.

**Comment by papandreou** [comment]
Much better: https://travis-ci.org/papandreou/inter/builds/102615479

**Comment by owcd** [comment]
Thanks, works like a charm.
