### ISSUE TITLE
Missing renderCurrency method

### ISSUE THREAD

**Issue by ragulka** [papandreou/inter#7]
It seems that there is currently no currency rendering method? The patterns are available in CLDR and the implementation shouldn't be too hard to figure out either.

The syntax could look like this:

```javascript
inter.load('en');
inter.renderCurrency( 10000.23, 'EUR' ); // €10,000.23
inter.renderCurrency( 10000.23, 'EUR', true ); // EUR10,000.23
```
The 2nd param is of course, the currency we want to see the results in. The 3rd param is borrowed from Google Closure's implementation where they let the user decide if they need a global or local representation of the currency symbol.

**Comment by mwoc** [comment]
This has been implemented a while ago, as renderCurrencyShort and renderCurrencyLong
