### ISSUE TITLE
renderPercentage expects numberSystemId instead of numDecimals

### ISSUE THREAD

**Issue by ragulka** [papandreou/inter#9]
See: https://github.com/papandreou/inter#interrenderpercentagenumber-numdecimals

Both `inter.renderPercentage` and `inter.getPercentageRenderer` should take a `numDecimals` argument, but instead they expect a `numberSystemId`.

I think they should definitely accept an argument that enables the user to control the number of decimals. Preferably even `minDecimals` and `maxDecimals`.

**Comment by mwoc** [comment]
This got fixed with v1.9.0
